//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Week02.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_HoaDon
    {
        public int ID_CTHD { get; set; }
        public int Ma_hd { get; set; }
        public int ID_sp { get; set; }
        public Nullable<int> So_luong { get; set; }
        public Nullable<int> Gia { get; set; }
    
        public virtual Hoa_don Hoa_don { get; set; }
        public virtual San_pham San_pham { get; set; }
    }
}
