//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Week02.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Khach_hang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Khach_hang()
        {
            this.Hoa_don = new HashSet<Hoa_don>();
        }
    
        public int ID_kh { get; set; }
        public string Ten_kh { get; set; }
        public string Email_kh { get; set; }
        public string Sdt_kh { get; set; }
        public string Diachi_kh { get; set; }
        public Nullable<System.DateTime> Ngaysinh_kh { get; set; }
        public string Mk_kh { get; set; }
        public string PQuyen_kh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hoa_don> Hoa_don { get; set; }
    }
}
