//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Week02.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nhan_hieu
    {
        public int ID_nhanhieu { get; set; }
        public string Ten_nhanhieu { get; set; }
        public string Mo_ta { get; set; }
    }
}
