//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Week02.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class San_pham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public San_pham()
        {
            this.CT_HoaDon = new HashSet<CT_HoaDon>();
        }
    
        public int ID_sp { get; set; }
        public string Ten_sp { get; set; }
        public string Nsx_sp { get; set; }
        public Nullable<int> Gia_sp { get; set; }
        public string Hinh_sp { get; set; }
        public string Mo_ta { get; set; }
        public int ID_nhom { get; set; }
        public Nullable<int> So_luong { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_HoaDon> CT_HoaDon { get; set; }
        public virtual Nhom_sp Nhom_sp { get; set; }
    }
}
